#98 forum api
shchegol/reactive-battle pull request #118
Opened 2021-02-18 21:10 UTC by zemer

fix #98 

При старте все таблицы сбросятся. Чуть позже это отключим.

Маршруты в этих файлах:
src/server/routes/commentRouterFactory.ts
src/server/routes/topicRouterFactory.ts
src/server/routes/userRouterFactory.ts

2021-02-19 09:56 UTC, shchegol requested changes
- [x] убрать модель user
- [ ] сделать привязку к юзеру через login (topic, comment)
- [ ] сделать прослойку /api/v1 для роутов относящихся к API

2021-02-20 10:56 UTC, shchegol approved these changes

2021-02-20 13:25 UTC, alexch365 approved these changes

2021-02-20 13:25 UTC, alexch365 commented on src/server/models/comment.ts
> +  paranoid: false,
эти строки можно убрать, т.к по умолчанию timestamps true, а paranoid false

2021-02-20 13:40 UTC, merged