#6 game
shchegol/reactive-battle pull request #19
Opened 2020-12-22 11:25 UTC by zemer

Страницы лидеров, ошибок, игры.
Рефакторинг компонентов.

2020-12-23 09:05 UTC, shchegol requested changes

2020-12-23 09:05 UTC, shchegol commented on src/components/button/Button.tsx
> +  <button type="button" className={className} onClick={otherProps.onClick}>{children}</button>
Предлагаю каждое отдельное свойство переносить на новую строчку, так легче работать со свойствами
```
<button 
    type="button" 
    className={className} 
    onClick={otherProps.onClick}
>
    {children}
</button>
```

2020-12-23 09:05 UTC, shchegol commented on src/components/leadersTable/LeadersTable.tsx
> +        onSearch={() => console.log('search')}
Вот здесь каждое свойство на отдельной строке, удобно же!

2020-12-23 09:05 UTC, shchegol commented on src/components/app/App.tsx
> +        <Route path="/error_5xx" component={Error5xx} />
В путях, как правило, используют минусы /error-404 /error-5xx

2020-12-23 09:05 UTC, shchegol commented on src/components/button/types.ts
> +};
Зачем это тут?

2020-12-23 09:05 UTC, shchegol commented on src/components/leadersItem/LeadersItem.tsx
> +  <div className="leaders-item" style={{ borderColor: positionColor(leader.position) }}>
style={{ borderColor: positionColor(leader.position) }} вот эта конструкция не нужна, подмену цветов правильнее делать через классы модификаторы, например leaders-item_color_first. Style перебьёт свойства в css, потом сложно будет наложить новые стили на объявленный style

2020-12-23 09:05 UTC, shchegol commented on src/components/leadersItem/LeadersItem.tsx
> +    <span className="user">{leader.user}</span>
Если по БЭМ, то leaders-item__user и всё что вложено в leaders-item и зависит от него тоже с __

2020-12-23 09:05 UTC, shchegol commented on src/components/leadersItem/leadersItem.scss
> +    align-items: center;
&__position {}
&__user {}
...

2020-12-23 09:05 UTC, shchegol commented on src/components/leadersItem/utils/positionColor.ts
> +      return '#E79C21';
эту конструкцию лучше сделать массивом и так как у нас там будут модификторы, то получится примерно так:
```
const positionColor = ['first', 'second', ...] // и по номеру получать значение. 
`leaders-item_color_${positionColor[leader.position]}`
```

2020-12-23 09:05 UTC, shchegol commented on src/pages/error_404/Error_404.tsx
> +    <h1 className="error_404__title">ERROR 404</h1>
Здесь правильнее будет так:
```
<header className="error-404">
    <h1 className="error-404__title">ERROR 404</h1>
```

2020-12-23 09:05 UTC, shchegol commented on src/pages/error_404/error_404.scss
> +.error_404 {
Ну и следовательно тут не будет пустоты, __root перейдёт сюда

2020-12-23 09:05 UTC, shchegol commented on src/pages/error_5xx/Error_5xx.tsx
> +  <div className="error_5xx__root">
Тут тоже: 
```
.error-5xx 
   .error-5xx__title
```

2020-12-23 09:05 UTC, shchegol commented on src/styles/common/_base.scss
> -.button {
Отлично!

2020-12-23 13:18 UTC, zemer commented on src/components/button/types.ts
> +};
Хотел передавать обработчики. Пока убрал.

2020-12-23 13:43 UTC, zemer commented on src/components/leadersTable/LeadersTable.tsx
> +        onSearch={() => console.log('search')}
Когда их много, я переношу. Но если по одному-два, оставляю. Впрочем, я не против.

2020-12-23 14:51 UTC, shchegol commented on src/components/app/App.tsx
> +import Error5xx from '@root/pages/error_5xx';
Старайся придерживаться на всём проекте camelCase, кроме url и html, там kebab-case

2020-12-23 14:51 UTC, shchegol commented on src/components/leadersItem/LeadersItem.tsx
> +    className={`leaders-item leaders-item_color_${positionColor[leader.position - 1]}`}
А если цвета нет?

2020-12-23 14:51 UTC, shchegol commented on src/components/leadersItem/leadersItem.scss
> +        border-color: #e79c21;
В идеале эти цвета надо вынести в variables

2020-12-23 14:51 UTC, shchegol approved these changes

2020-12-23 15:07 UTC, alexch365 commented on src/components/button/Button.tsx
> +    type="button"
может type тоже в props вынести?

2020-12-23 15:07 UTC, alexch365 commented on src/pages/leaderborad/Leaderboard.tsx
> +export default function SignIn() {
Leaderboard()?

2020-12-23 19:21 UTC, zemer commented on src/pages/leaderborad/Leaderboard.tsx
> +export default function SignIn() {
Да, конечно.

2020-12-23 19:25 UTC, zemer commented on src/components/button/Button.tsx
> +    type="button"
Давай после мержа этой ветки и авторизации

2020-12-23 19:33 UTC, zemer commented on src/components/leadersItem/LeadersItem.tsx
> +    className={`leaders-item leaders-item_color_${positionColor[leader.position - 1]}`}
Тогда по умолчанию. Но для ясности вынес.

2020-12-23 19:35 UTC, alexch365 commented on src/components/button/Button.tsx
> +    type="button"
ок

2020-12-23 19:35 UTC, alexch365 approved these changes

2020-12-24 11:12 UTC, shchegol commented on src/components/leadersItem/LeadersItem.tsx
> +    className={`leaders-item leaders-item_color_${positionColor[leader.position - 1]}`}
Если нет цвета, то leaders-item_color_ тоже не нужен, цвет по умолчанию leaders-itemдолжен содержать.

2020-12-24 14:16 UTC, pashakhorikov approved these changes
Можно улучшить качество и вовлчеенность всех участников ревью, сделав PR размером в два три файла - одна фича - один PR, 48 файлов от сматривать тяжело.

2020-12-24 14:16 UTC, pashakhorikov commented on src/components/app/App.tsx
> +import Error5xx from '@root/pages/error_5xx';
Если создавать отдельный компонент на каждую ошибку, то придется напложить множетсов файлов. Можно лучше, например, создать один компонент который пригимает параметры ошибки и както их рендерит.

2020-12-24 14:16 UTC, pashakhorikov commented on src/components/app/App.tsx
> +import Error5xx from '@root/pages/error5xx';
Можно не создавать на кажду группу ошибок компонент. Достаточно создать Error и разреливать внутри одного компонента всё.

2020-12-24 14:16 UTC, pashakhorikov commented on src/components/leadersItem/LeadersItem.tsx
> +const getTopPlacesColor = (position: number): string => {
Можно лучше, вынести, скажем функцию полуения цвета борды в завимости от места игрока в стратегию и вызывать ее уже через имеорр в компонент.

2020-12-24 14:16 UTC, pashakhorikov commented on src/components/playground/Playground.tsx
> +  useEffect(() => {
можно лучше сделать:  
useEffect(() => {
  let isCurrentContext = context.current
   if (isCurrentContext) {
      setContext(context)
    }
  return () => {
    isCurrentContext = false
  }
}, [])

Зависимость [] будет учитываться при использовании эффекта и поможет избежать багов, так же не стоит забываь про функцию очистки. 

`
return () => {
    isCurrentContext = false
  }
`

Хорошо про захваты состояний написано тут.

2020-12-24 14:16 UTC, merged